### ISSUE TITLE
How to update the plugin?

### ISSUE THREAD

**Issue by Chrisedmo** [70kft/craft-instablog#10]
i have a notification to update the plugin to 1.2, so I downloaded the plugin form the admin. Then copied across then new files and replaced the ones in my install. Everything seems ok, but i still have the update notification?

**Comment by jpwdesigns** [comment]
So I facepalmed when I saw this. I had forgotten to update the version number in the config. You have the latest. To get rid of the update notice just change the version number in the base file to 1.2 or download again. Sorry for the annoyance.
