### ISSUE TITLE
Multiple blogs, into different categories

### ISSUE THREAD

**Issue by ow** [70kft/craft-instablog#13]
Hi there,

I need to migrate a few blogs into Craft. Is there a way to do this, putting them into the same entries area, but giving them all separate categories?

**Comment by jpwdesigns** [comment]
Hi @hyperperforator,

The plugin pulls in whatever categories and tags are in wordpress before you export. Technically you could manually update categories in wordpress before doing export/import into craft. May be slightly tedious but there's no way to override the plugin categories at the moment.
