### ISSUE TITLE
Error when importing WP blog

### ISSUE THREAD

**Issue by davidteal** [70kft/craft-instablog#14]
Hi there.

Just spent a couple of hours debugging an issue with the import and the issue was caused by line 239 in InstaBlog_ImportService.php. This should probably check to see if a featured image is returned as otherwise, the saveEntry call fails e.g.

`$importFeaturedImage = $this->_importFeaturedImage($settings, $post['post_link'], $baseUrl);`
            `if ($importFeaturedImage) {`
                `$featuredImage[] = $importFeaturedImage;`
           `}`

Can submit PR if you'd like.

Cheers.

**Comment by jpwdesigns** [comment]
Hey thanks for finding the issue. If you don't mind sending a pull request
I'll get it merged in.
