### ISSUE TITLE
Wordpress Import Error

### ISSUE THREAD

**Issue by Etabat** [70kft/craft-instablog#15]
I can successfully upload the Wordpress XML file but when I click import it gives me a HTTP ERROR 500. This is on the production website.
However I was able to import and get Instablog running on my localhost with MAMP as the server.
I suspect this might be a permission issue on the production server (AWS). 
Thoughts?

**Comment by Etabat** [comment]
After checking the phperrors.log I noticed this error:
[06-Apr-2017 19:10:18 UTC] PHP Parse error:  syntax error, unexpected '.', expecting ')' in /var/www/html/production/craft/plugins/instablog/services/InstaBlog_ImportService.php on line 156

Strange that this occurs only on the production server and not localhost.

**Comment by jpwdesigns** [comment]
Fixed by https://github.com/70kft/craft-instablog/commit/2c1bca672be30412aa697de93ed0750ac1eee7b1
