### ISSUE TITLE
Craft 2.5 incompatibility

### ISSUE THREAD

**Issue by lukeholder** [70kft/craft-instablog#3]
The plugin's icon for Craft 2.5 is missing (https://craftcms.com/support/updating-plugins-for-craft-2.5) and the link in the control panel settings is broken:

![](https://storage.jumpshare.com/preview/7YkCmZUUrH66zEdwOY793KV_KCftwR77ZrEv4hL7bgbZm3Bz18M5f0Vf9J9deDzj7yTWmDbz95_Gd3ORkM_Wnd0Iq-_ZMIwlJNqsu6s4bO0F1kR3dMUjedqC16uBUu85)

Thanks for this great plugin!

**Comment by jpwdesigns** [comment]
Thanks for heads up. I'll look into an update for this.

**Comment by jpwdesigns** [comment]
Ok, got a designer working on the icon ;)

**Comment by jpwdesigns** [comment]
Also, I may be missing something @lukeholder but in my base plugin class I have this:
`public function getSettingsUrl()
  {
    return UrlHelper::getUrl('/instablog/settings');
  }`

Which works correctly on the plugin's page but breaks on the settings page. If I remove the root relative leading slash '/' it works correctly on the settings page but breaks completely on the plugins page. What is the correct method to insure both are working?

**Comment by lukeholder** [comment]
No need for the wrapping with UrlHelper:

```
public function getSettingsUrl()
{
    return 'commerce/settings/general';
}
```

**Comment by jpwdesigns** [comment]
Ok awesome, just saw that in the docs. Thanks!

**Comment by jpwdesigns** [comment]
Fixed in https://github.com/70kft/craft-instablog/commit/68b9c0c715ea566dab4c90954b12278278a3b45e
