### ISSUE TITLE
Craft\EntryModel and its behaviors do not have a method or closure named "body".

### ISSUE THREAD

**Issue by jacobgraf** [70kft/craft-instablog#5]
When viewing the single entry page for the default blog entry that's created on install, I get this error.

`Craft\EntryModel and its behaviors do not have a method or closure named "body".`

**Comment by jpwdesigns** [comment]
Hi @jacobgraf 
Did you discover what the problem was? I suspect that is related to a var in your layout or something that was changed in the InstaBlog template.

**Comment by jacobgraf** [comment]
No, unfortunately I had to give up and uninstall it. :-(

**Comment by jpwdesigns** [comment]
Was this just a plain install without modding anything?

**Comment by pj258** [comment]
line 27 in **_instablog-layout.twig**
<meta property="og:description"  content="{{ entry.postDate.format('M d, Y') }} - {{ entry.body|striptags|truncate(180) }}">

change entry.body to entry.instaBlogBody

**Comment by jpwdesigns** [comment]
Thank you @pj258 this has been updated.
