### ISSUE TITLE
Specific Tags redirect to Craft's 404

### ISSUE THREAD

**Issue by shunluoifong** [70kft/craft-instablog#7]
Other than changing my blog url from "blog" to "insights", I'm using the Instablog plugin pretty much as is, at least to get started. I'm applying tags to my entries using the instablogTag field, and when I browse to /insights/tags, it lists out all the tags (per the tag.twig file). However, if I click a specific tag that's listed, and it takes me to (for example) /insights/tags/tag-name, it is displaying Craft's 404 template (404.html). 

In tag.twig it has the code:

`{% if craft.request.segment(3) == '' %}
...
{% else %}
...
{% endif %}`

So, at /insights/tag it enters the if statement, but at /insights/tag/tag-name it won't even go into the else statement. It just displays 404.html.

Any advise for troubleshooting?

**Comment by shunluoifong** [comment]
Kind of quiet here...any activity on this plugin?

**Comment by jpwdesigns** [comment]
Hi @shunluoifong I'm checking

**Comment by jpwdesigns** [comment]
If you are getting the instablog 404 with Nicholas Cage ;) then the routing is finding the blog template correctly but it isn't finding a tag. For example. if in the case of the URL /insights/tag/some-tag-name and some-tag-name doesn't exist then it should throw a 404. However if you are getting your theme 404 then the routing is not resolving correctly.

I would check the following:
1. Did you change the folder name for `/templates/blog` to `/templates/insights`?
2. If so check the markup of all of the templates for mentions of the folder path `blog/...` and change to `insights/...`
3. If you did not change the template folder name I suggest doing so and updating the template paths as well as any link paths that refer to `blog`.
4. Go to Settings > Sections and note the URL format for InstaBlog. It should be `insights/{slug}`
5. While on Settings > Sections > InstaBlog also update Entry Template to be `insights/_entry`
6. Go to Settings > Routes. You'll see 2 entries there for blog. Update them accordingly and that should get you running. **This may be the only thing you're missing.**
7. Go to Settings > Categories > InstaBlog Categories and update the Category URL Format as well as the Category Template Path.
8. Finally, just to be on the safe side go to Settings > Clear Caches and dump everything.

That should cover just about everything. Let me know if this helps.

**Comment by shunluoifong** [comment]
Ah, those routes...that was it. Thanks for the response. This is also a helpful list to step through whenever I change the name/url of the blog. Thanks!

**Comment by jpwdesigns** [comment]
Awesome. Glad that helped!
