### ISSUE TITLE
Install failed on Craft Personal

### ISSUE THREAD

**Issue by tom-c** [70kft/craft-instablog#9]
Just trying this out on a basic install (personal) - removed the existing section as suggested but receive this error:

Craft\SectionsService and its behaviors do not have a method or closure named "canHaveMore".

Any ideas?

**Comment by jpwdesigns** [comment]
Hey yeah looks like craft removed a method from Sections Service. I'll put a fix together.

**Comment by tom-c** [comment]
Thanks! It works fine locally with a client licence trail, so it's specific to the personal licence.

**Comment by jpwdesigns** [comment]
Ok i've fixed the problem please download and try again.

**Comment by tom-c** [comment]
Thank you - will test this week on another virgin install and let you know :)
